### ISSUE TITLE
Ionic Login Error

### ISSUE THREAD

**Issue by clarkmcnally** [bitrise-community/steps-ionic-archive#10]
This was working fine earlier today and suddenly stopped working, it looks like on my previous builds it never even tried running `ionic cordova resources`

![image](https://user-images.githubusercontent.com/7518224/30344742-240a522c-97c8-11e7-8362-237311ab8d52.png)

**Comment by clarkmcnally** [comment]
Issue is still occurring, has anyone else seen this issue?

**Comment by bloodrabbit** [comment]
Thank you for reporting @clarkmcnally - we'll look into this asap!

**Comment by clarkmcnally** [comment]
Was there ever a resolution for this?

**Comment by godrei** [comment]
Hi @clarkmcnally ,
sorry for my late response!
We released a new version ([v1.0.0](https://github.com/bitrise-community/steps-ionic-archive/releases/tag/1.0.0)) of the step.
Use `ionic_username` and `ionic_password` inputs to login using the ionic-cli.
