### ISSUE TITLE
Using wrong Code Sign Identity

### ISSUE THREAD

**Issue by clarkmcnally** [bitrise-community/steps-ionic-archive#13]
Archive step appears to be using the wrong code signing identity, it is using `iOS Development` instead of `iPhone Developer` that was specified in the cordova build config. This was working fine last week.

<img width="888" alt="screen shot 2017-09-20 at 3 30 53 pm" src="https://user-images.githubusercontent.com/7518224/30666075-cf01a12a-9e18-11e7-9bb0-1aeeef9cf58f.png">
<img width="1289" alt="screen shot 2017-09-20 at 3 31 09 pm" src="https://user-images.githubusercontent.com/7518224/30666073-cd65a2d0-9e18-11e7-8ab1-ed3fff4edbf1.png">

**Comment by godrei** [comment]
Hi, could you please attach your full build log file?
