### ISSUE TITLE
cli-plugin-ionic-angular is no longer needed

### ISSUE THREAD

**Issue by davidpp** [bitrise-community/steps-ionic-archive#20]
npm "install" "@ionic/cli-plugin-ionic-angular@latest" "@ionic/cli-plugin-cordova@latest"
command failed, error: command failed, output: npm WARN deprecated @ionic/cli-plugin-cordova@1.6.2: Ionic CLI 3.8 no longer loads this plugin. See https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#3.8.0

**Comment by erosdome** [comment]
Hi, thanks for reporting, it seems an update is due for this step then. We will update it ASAP.

**Comment by davidpp** [comment]
Solved by #21
