### ISSUE TITLE
FEATURE: Option to disable the removing of platforms.

### ISSUE THREAD

**Issue by WillPoulson** [bitrise-community/steps-ionic-archive#24]
Hi,

I would like the option to be able to disable the removing of platforms as I'm trying to cache my generated platforms plugins to significantly reduce my build times and downloading and installing the plugins takes up to 6 mins of my build. 

Just a simple true/false would do the job, just anything to allow us to be able to disable it if we don't want it.

Please note I of course still want it to add the platforms, just optional removals of platforms.

Thanks!

**Comment by doomsayer13** [comment]
Hi @WillPoulson 
Thanks for requesting a feature.

**Comment by WillPoulson** [comment]
I've implemented this myself and just created a pull request for it. #25

**Comment by godrei** [comment]
Hi we added this in the version: [1.2.4](https://github.com/bitrise-community/steps-ionic-archive/releases/tag/1.2.4).
