### ISSUE TITLE
FEATURE : Option to pass environment variable to Ionic build

### ISSUE THREAD

**Issue by olamarche** [bitrise-community/steps-ionic-archive#31]
Based on this project : https://github.com/gshigeto/ionic-environment-variables
We can build contextual ionic app based on environment variable. It could be nice to have an option in this steps to build multiple environment app.

Did you have planned something similar ?

**Comment by godrei** [comment]
Hi @olamarche ,
could you please highlight a little bit, what changes would be required to solve to build multiple environment app?

**Comment by olamarche** [comment]
I ended up using env. vars from bitrise settings and my build passed. Thank you
