### ISSUE TITLE
Not adding android to cordova add platform command

### ISSUE THREAD

**Issue by clarkmcnally** [bitrise-community/steps-ionic-archive#9]
Added screenshot from bitrise build log

![image](https://user-images.githubusercontent.com/7518224/30065563-ef4f2c68-921a-11e7-8702-27246db91adf.png)

**Comment by viktorbenei** [comment]
Thanks for reporting @clarkmcnally , we'll check this ASAP! :)

**Comment by godrei** [comment]
Hi @clarkmcnally ,
thanks for the issue report!
We released a new version ([0.9.5](https://github.com/bitrise-community/steps-ionic-archive/releases/tag/0.9.5)) of the step, the new version contains fix for the `ionic cordova` commands.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
